/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Warkarma (https://sketchfab.com/warkarma)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dungeon-low-poly-game-level-challenge-0fd0d477d7424e5d8915ce0c06a2920d
title: Dungeon - Low Poly Game Level Challenge
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gltfUrl from "../src/models/island_house_copy.gltf?url";
import { useLayoutEffect } from "react";
import create from "zustand";
import { Box3, MeshStandardMaterial, Vector3 } from "three";

useGLTF.preload(gltfUrl);

export const useStore = create((set) => ({
  nodes: [],
  playerRef: null,
  setPlayerRef: (playerRef) => set((state) => ({ ...state, playerRef })),
  velocity: new Vector3(),
  getDeltaVector: () => new Vector3(),
  onGround: false,
  setOnGround: (onGround) => set((state) => ({ ...state, onGround })),
  setGetDeltaVector: (fn) => set((state) => ({ ...state, getDeltaVector: fn })),
  setNodes: (nodes) => set((state) => ({ ...state, nodes })),
  addNode: (node) =>
    set((state) => ({ ...state, nodes: [...state.nodes, node] })),
}));

export default function Model({ ref, ...props }) {
  const innerRef = useRef();
  const group = ref ?? innerRef;
  const { nodes, materials } = useGLTF(gltfUrl);
  const setNodes = useStore((state) => state.setNodes);
  const addNode = useStore((state) => state.addNode);
  useLayoutEffect(() => {
    const box = new Box3();
    box.setFromObject(group.current);
    box.getCenter(group.current.position).negate();
    group.current.updateMatrixWorld(true);

    setNodes([]);
    setTimeout(() => group.current.traverse(addNode), 1000);
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[489.02, 374.86, -222.79]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ellipse_2.geometry}
          material={nodes.Ellipse_2.material}
          position={[16.69, 0.26, -6.82]}
          rotation={[-0.05, 0.44, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_3.geometry}
          material={nodes.Rectangle_3.material}
          position={[0, -0.09, 0]}
          rotation={[-0.05, 0.44, -Math.PI / 2]}
        />
      </group>
      <group position={[343.1, 261.1, -76.34]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_12.geometry}
          material={nodes.Cube_12.material}
          position={[1.59, -63.45, 140.17]}
          rotation={[Math.PI, 1.35, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_11.geometry}
          material={nodes.Cube_11.material}
          position={[-2.43, -45.12, 125.84]}
          rotation={[-Math.PI, 1.35, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_15.geometry}
          material={nodes.Cube_15.material}
          position={[128.21, 50.45, -137.01]}
          rotation={[-Math.PI, 1.17, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_14.geometry}
          material={nodes.Cube_14.material}
          position={[153.78, 43.51, -118.28]}
          rotation={[-Math.PI, 1.37, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_13.geometry}
          material={nodes.Cube_13.material}
          position={[157.95, 12.13, -90.21]}
          rotation={[-Math.PI, 1.37, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_10.geometry}
          material={nodes.Cube_10.material}
          position={[-19.43, -29.77, 97.41]}
          rotation={[-Math.PI, 1.37, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_9.geometry}
          material={nodes.Cube_9.material}
          position={[-128.72, -37.21, 107.41]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
      </group>
      <group position={[197.79, 295.35, 21]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ellipse.geometry}
          material={nodes.Ellipse.material}
          position={[1.11, -4.32, -20]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle.geometry}
          material={nodes.Rectangle.material}
          position={[0.21, -1.5, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_2.geometry}
          material={nodes.Rectangle_2.material}
          position={[-1.11, 0, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
      </group>
      <group position={[795.24, 568.84, -368.8]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_7.geometry}
          material={nodes.Cube_7.material}
          position={[132.57, -100.64, 312.66]}
          rotation={[1.51, -0.32, 1.14]}
          scale={[0.69, 0.69, 0.49]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_6.geometry}
          material={nodes.Cube_6.material}
          position={[136.08, 127.87, -225.51]}
          rotation={[2.14, -0.48, 0.49]}
          scale={[0.69, 0.69, 0.49]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_5.geometry}
          material={nodes.Cube_5.material}
          position={[80.34, 218.98, 15.99]}
          rotation={[1.43, 0.32, 0.17]}
          scale={[0.85, 0.85, 0.61]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_8.geometry}
          material={nodes.Cube_8.material}
          position={[-37.6, -293.91, -301.11]}
          rotation={[0.98, -0.43, -0.19]}
          scale={[0.6, 0.6, 0.43]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4.geometry}
          material={nodes.Cube_4.material}
          position={[-149.26, 270.7, -51.29]}
          rotation={[0.62, 0.54, -0.35]}
          scale={[0.93, 0.93, 0.66]}
        />
      </group>
      <group position={[-18, 25.76, 58]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[770.95, -57.01, 481.96]}
          rotation={[0, Math.PI / 3, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={nodes.Cube_1.material}
          position={[800.25, -57.01, -425.17]}
          rotation={[-Math.PI, Math.PI / 3, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={nodes.Cube_2.material}
          position={[31.91, -57.01, -905.42]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={nodes.Cube_3.material}
          position={[-756.28, -57.01, -473.49]}
          rotation={[-Math.PI, -Math.PI / 3, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_16.geometry}
          material={nodes.Cube_16.material}
          position={[-788.19, -57.01, 418.21]}
          rotation={[0, -Math.PI / 3, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_17.geometry}
          material={nodes.Cube_17.material}
          position={[-31.91, -57.01, 896.78]}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
      <group position={[96.16, 232.05, 62.57]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_20.geometry}
          material={nodes.Rectangle_20.material}
          position={[261.96, 55.64, -152.21]}
          rotation={[0, 1.5, -Math.PI / 2]}
          scale={[0.78, 0.78, 0.78]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_19.geometry}
          material={nodes.Rectangle_19.material}
          position={[257.74, 49.96, -126.16]}
          rotation={[0.05, 1.24, -1.56]}
          scale={[0.73, 0.73, 0.73]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_18.geometry}
          material={nodes.Rectangle_18.material}
          position={[246.65, 42.12, -99.06]}
          rotation={[0, 1.15, -Math.PI / 2]}
          scale={[0.94, 0.94, 0.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_17.geometry}
          material={nodes.Rectangle_17.material}
          position={[231.89, 32.63, -75.34]}
          rotation={[-0.1, 0.71, -1.58]}
          scale={[0.83, 0.83, 0.83]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_16.geometry}
          material={nodes.Rectangle_16.material}
          position={[197.61, -37.76, 71.88]}
          rotation={[0, 0.89, -1.55]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_15.geometry}
          material={nodes.Rectangle_15.material}
          position={[178.5, -45.02, 98.08]}
          rotation={[-0.14, 0.89, -1.53]}
          scale={[0.92, 0.92, 0.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_14.geometry}
          material={nodes.Rectangle_14.material}
          position={[153.89, -53.99, 125.09]}
          rotation={[0, 0.8, -1.64]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_13.geometry}
          material={nodes.Rectangle_13.material}
          position={[128.2, -53.99, 144.81]}
          rotation={[0, 0.54, -1.49]}
          scale={[1, 0.84, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_12.geometry}
          material={nodes.Rectangle_12.material}
          position={[98.25, -47.85, 150.34]}
          rotation={[0, -0.07, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_11.geometry}
          material={nodes.Rectangle_11.material}
          position={[66.05, -41.76, 148.05]}
          rotation={[0, -0.07, -1.66]}
          scale={[0.91, 0.91, 0.91]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_10.geometry}
          material={nodes.Rectangle_10.material}
          position={[33.83, -39.34, 145.76]}
          rotation={[0, -0.07, -1.61]}
          scale={[1, 0.79, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_9.geometry}
          material={nodes.Rectangle_9.material}
          position={[0.57, -32.45, 143.39]}
          rotation={[0, -0.07, -1.68]}
          scale={[1.06, 1.06, 1.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_8.geometry}
          material={nodes.Rectangle_8.material}
          position={[-38.18, -27.89, 140.64]}
          rotation={[0, -0.07, -Math.PI / 2]}
          scale={[0.9, 0.9, 0.9]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_7.geometry}
          material={nodes.Rectangle_7.material}
          position={[-71.99, -24.86, 138.23]}
          rotation={[0, -0.07, -1.52]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_6.geometry}
          material={nodes.Rectangle_6.material}
          position={[-101.92, -21.48, 136.11]}
          rotation={[0, -0.07, -Math.PI / 2]}
          scale={[1, 0.84, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_5.geometry}
          material={nodes.Rectangle_5.material}
          position={[-138.01, -21.48, 133.54]}
          rotation={[0, -0.07, -1.65]}
          scale={[1.08, 1.08, 1.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_4.geometry}
          material={nodes.Rectangle_4.material}
          position={[-171.25, -21.48, 131.18]}
          rotation={[0, -0.07, -1.47]}
          scale={[0.89, 0.89, 0.89]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_3_1.geometry}
          material={nodes.Rectangle_3_1.material}
          position={[-201.59, -21.48, 129.02]}
          rotation={[0, -0.07, -Math.PI / 2]}
          scale={[0.93, 0.93, 0.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_2_1.geometry}
          material={nodes.Rectangle_2_1.material}
          position={[-231.57, -21.48, 123.43]}
          rotation={[0, -0.26, -Math.PI / 2]}
          scale={[0.93, 0.74, 0.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_1.geometry}
          material={nodes.Rectangle_1.material}
          position={[-256.18, -21.48, 108.96]}
          rotation={[0, -0.7, -Math.PI / 2]}
          scale={[0.93, 0.93, 0.93]}
        />
      </group>
      <group position={[65.54, 391.65, -64.6]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_43.geometry}
          material={nodes.Cube_43.material}
          position={[-17.54, 88.32, -6.4]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_42.geometry}
          material={nodes.Cube_42.material}
          position={[-17.54, 76.98, -6.4]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_40.geometry}
          material={nodes.Cube_40.material}
          position={[-90.54, -100.6, -145.86]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[1, 1, 0.4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_39.geometry}
          material={nodes.Cube_39.material}
          position={[-90.54, -10.49, -145.86]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[1, 1, 0.4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_23.geometry}
          material={nodes.Cube_23.material}
          position={[-175.78, -122.01, 67.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_20.geometry}
          material={nodes.Cube_20.material}
          position={[-78.09, -87.06, 132.61]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_8_1.geometry}
          material={nodes.Cube_8_1.material}
          position={[-78.09, -87.06, 135.54]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_13_1.geometry}
          material={nodes.Cube_13_1.material}
          position={[54.43, -46.53, 170.07]}
          scale={[1, 1, 1.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_16_1.geometry}
          material={nodes.Cube_16_1.material}
          position={[92.97, -92.59, 160.77]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_15_1.geometry}
          material={nodes.Cube_15_1.material}
          position={[15.35, -92.01, 160.77]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_16_2.geometry}
          material={nodes.Cube_16_2.material}
          position={[92.97, -92.59, 177.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_18.geometry}
          material={nodes.Cube_18.material}
          position={[53.67, -92.01, 177.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_14_1.geometry}
          material={nodes.Cube_14_1.material}
          position={[15.35, -92.01, 177.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_29.geometry}
          material={nodes.Cube_29.material}
          position={[-166.8, -66.05, 21.98]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_30.geometry}
          material={nodes.Cube_30.material}
          position={[-198.14, -66.05, 67.21]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_28.geometry}
          material={nodes.Cube_28.material}
          position={[-198.14, -66.05, 21.98]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_27.geometry}
          material={nodes.Cube_27.material}
          position={[-198.14, -66.05, 114.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_17_1.geometry}
          material={nodes.Cube_17_1.material}
          position={[54.43, -131.66, 170.07]}
          scale={[1, 1, 1.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_12_1.geometry}
          material={nodes.Cube_12_1.material}
          position={[54.43, -52.63, 170.07]}
          scale={[1, 1, 1.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_11_1.geometry}
          material={nodes.Cube_11_1.material}
          position={[54.3, -92, 167.6]}
          scale={[1, 1, 1.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_19.geometry}
          material={nodes.Cube_19.material}
          position={[54.3, 30.01, 160.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_10_1.geometry}
          material={nodes.Cube_10_1.material}
          position={[54.3, 30.01, 162.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_41.geometry}
          material={nodes.Cube_41.material}
          position={[-167.14, 41.97, -95.83]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_22.geometry}
          material={nodes.Cube_22.material}
          position={[-166.93, 20.24, 61.54]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.76, 0.76, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_38.geometry}
          material={nodes.Cube_38.material}
          position={[-90.97, -60.95, -140.66]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.89, 0.89, 0.89]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_37.geometry}
          material={nodes.Cube_37.material}
          position={[-90.97, 28.26, -140.66]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.89, 0.89, 0.89]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_36.geometry}
          material={nodes.Cube_36.material}
          position={[51.09, 28.26, -180.94]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.76, 0.76, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_35.geometry}
          material={nodes.Cube_35.material}
          position={[132.9, 30.01, -74.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.66}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_31.geometry}
          material={nodes.Cube_31.material}
          position={[132.69, 30.01, 52.57]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_21.geometry}
          material={nodes.Cube_21.material}
          position={[-78.09, 30.01, 131.07]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_24.geometry}
          material={nodes.Cube_24.material}
          position={[-177.79, -66.12, 68.03]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.76, 0.76, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_41_1.geometry}
          material={nodes.Cube_41_1.material}
          position={[-167.86, 41.97, -95.83]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_22_1.geometry}
          material={nodes.Cube_22_1.material}
          position={[-168.24, 20.24, 61.54]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.76, 0.76, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_38_1.geometry}
          material={nodes.Cube_38_1.material}
          position={[-90.97, -60.95, -142.2]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.89, 0.89, 0.89]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_37_1.geometry}
          material={nodes.Cube_37_1.material}
          position={[-90.97, 28.26, -142.2]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.89, 0.89, 0.89]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_36_1.geometry}
          material={nodes.Cube_36_1.material}
          position={[51.09, 28.26, -182.25]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.76, 0.76, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_35_1.geometry}
          material={nodes.Cube_35_1.material}
          position={[134.03, 30.01, -74.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.66}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_31_1.geometry}
          material={nodes.Cube_31_1.material}
          position={[134.41, 30.01, 52.57]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_7_1.geometry}
          material={nodes.Cube_7_1.material}
          position={[-78.09, 30.01, 132.8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_9_1.geometry}
          material={nodes.Cube_9_1.material}
          position={[-189.87, 6, -95.22]}
          rotation={[-Math.PI / 2, -0.48, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_6_1.geometry}
          material={nodes.Cube_6_1.material}
          position={[-163.6, -43.44, 156.79]}
          rotation={[-1.09, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_9_2.geometry}
          material={nodes.Cube_9_2.material}
          position={[-186.75, 0.02, -95.22]}
          rotation={[-Math.PI / 2, -0.48, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_5_1.geometry}
          material={nodes.Cube_5_1.material}
          position={[-163.6, -49.39, 153.69]}
          rotation={[-1.09, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_26.geometry}
          material={nodes.Cube_26.material}
          position={[-180.28, -29.4, 75.8]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_25.geometry}
          material={nodes.Cube_25.material}
          position={[-180.28, -35.6, 74.3]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_9_3.geometry}
          material={nodes.Cube_9_3.material}
          position={[-174.97, -62.98, -95.4]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_1.geometry}
          material={nodes.Cube_4_1.material}
          position={[-163.79, -112.59, 142.21]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_31_2.geometry}
          material={nodes.Cube_31_2.material}
          position={[143.83, -9.56, 53.44]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3_1.geometry}
          material={nodes.Cube_3_1.material}
          position={[-78.96, -9.56, 142.21]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_34.geometry}
          material={nodes.Cube_34.material}
          position={[167.04, -26.25, -71.25]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_33.geometry}
          material={nodes.Cube_33.material}
          position={[167.04, -30.4, -71.25]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_32.geometry}
          material={nodes.Cube_32.material}
          position={[167.04, -84.57, -71.25]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2_1.geometry}
          material={nodes.Cube_2_1.material}
          position={[50.31, -57.07, -10.72]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_44.geometry}
          material={nodes.Cube_44.material}
          position={[-17.4, -45.07, -4.57]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-128.78, -38, -86.79]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosahedron_4.geometry}
          material={nodes.Icosahedron_4.material}
          position={[599.92, 346.06, -51.86]}
          rotation={[-2.31, 0.9, -0.17]}
          scale={[0.76, 0.76, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosahedron_3.geometry}
          material={nodes.Icosahedron_3.material}
          position={[-285.34, -52.36, 1044.1]}
          rotation={[-2.53, 0.64, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosahedron_2.geometry}
          material={nodes.Icosahedron_2.material}
          position={[304.41, -198.21, -782.78]}
          rotation={[-2.53, 0.64, 0.15]}
          scale={[1.92, 1.92, 1.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosahedron.geometry}
          material={nodes.Icosahedron.material}
          position={[-423.87, -105.57, -898.95]}
          rotation={[-2.44, 0.02, 0.49]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_2.geometry}
          material={nodes.Cube_4_2.material}
          position={[-1018.37, -131.14, -717.89]}
          rotation={[-1.54, -0.41, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_15_2.geometry}
          material={nodes.Cube_15_2.material}
          position={[1229.77, -100.57, 498.2]}
          rotation={[-0.88, 0.49, -0.58]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2_2.geometry}
          material={nodes.Cube_2_2.material}
          position={[-203.15, -25.28, -783.44]}
          rotation={[-0.88, 0.49, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_22_2.geometry}
          material={nodes.Cube_22_2.material}
          position={[-86.08, 231.88, 178.99]}
          rotation={[-1.56, -1.43, 0.06]}
          scale={[-1, 1, 3.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_21_1.geometry}
          material={nodes.Cube_21_1.material}
          position={[301.9, 291.28, -353.44]}
          rotation={[-0.4, 0.19, -2.01]}
          scale={[1, 1, 1.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_20_1.geometry}
          material={nodes.Cube_20_1.material}
          position={[-98.21, -49.67, 1082.08]}
          rotation={[-0.63, -0.38, -2.35]}
          scale={[1, 1, 1.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3_2.geometry}
          material={nodes.Cube_3_2.material}
          position={[662.83, -193.05, -710.04]}
          rotation={[-0.63, -0.38, -2.35]}
          scale={[1.92, 1.92, 2.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_23_1.geometry}
          material={nodes.Cube_23_1.material}
          position={[-17.57, 2.82, 684.29]}
          rotation={[-0.59, -0.34, 1.54]}
          scale={[1, 1, 1.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_45.geometry}
          material={nodes.Cube_45.material}
          position={[-502.08, -121.33, -703.03]}
          rotation={[-2.21, -0.45, 1.23]}
          scale={[1, 1, 1.17]}
        />
      </group>
      <group position={[-186.78, -36, -70.79]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosahedron_4_1.geometry}
          material={nodes.Icosahedron_4_1.material}
          position={[599.92, 346.06, -51.86]}
          rotation={[-2.31, 0.9, -0.17]}
          scale={[0.76, 0.76, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosahedron_3_1.geometry}
          material={nodes.Icosahedron_3_1.material}
          position={[-285.34, -52.36, 1044.1]}
          rotation={[-2.53, 0.64, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosahedron_2_1.geometry}
          material={nodes.Icosahedron_2_1.material}
          position={[304.41, -198.21, -782.78]}
          rotation={[-2.53, 0.64, 0.15]}
          scale={[1.92, 1.92, 1.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosahedron_1.geometry}
          material={nodes.Icosahedron_1.material}
          position={[-423.87, -105.57, -898.95]}
          rotation={[-2.44, 0.02, 0.49]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_3.geometry}
          material={nodes.Cube_4_3.material}
          position={[-1018.37, -131.14, -717.89]}
          rotation={[-1.54, -0.41, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_15_3.geometry}
          material={nodes.Cube_15_3.material}
          position={[1229.77, -100.57, 498.2]}
          rotation={[-0.88, 0.49, -0.58]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2_3.geometry}
          material={nodes.Cube_2_3.material}
          position={[-203.15, -25.28, -783.44]}
          rotation={[-0.88, 0.49, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_22_3.geometry}
          material={nodes.Cube_22_3.material}
          position={[-86.08, 231.88, 178.99]}
          rotation={[-1.56, -1.43, 0.06]}
          scale={[-1, 1, 3.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_21_2.geometry}
          material={nodes.Cube_21_2.material}
          position={[301.9, 291.28, -353.44]}
          rotation={[-0.4, 0.19, -2.01]}
          scale={[1, 1, 1.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_20_2.geometry}
          material={nodes.Cube_20_2.material}
          position={[-98.21, -49.67, 1082.08]}
          rotation={[-0.63, -0.38, -2.35]}
          scale={[1, 1, 1.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3_3.geometry}
          material={nodes.Cube_3_3.material}
          position={[662.83, -193.05, -710.04]}
          rotation={[-0.63, -0.38, -2.35]}
          scale={[1.92, 1.92, 2.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_23_2.geometry}
          material={nodes.Cube_23_2.material}
          position={[-17.57, 2.82, 684.29]}
          rotation={[-0.59, -0.34, 1.54]}
          scale={[1, 1, 1.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_46.geometry}
          material={nodes.Cube_46.material}
          position={[-502.08, -121.33, -703.03]}
          rotation={[-2.21, -0.45, 1.23]}
          scale={[1, 1, 1.17]}
        />
      </group>
      <group position={[-511.47, 190.72, 464.53]} rotation={[1.55, -1.33, 1.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2_4.geometry}
          material={nodes.Cube_2_4.material}
          position={[135.17, -56, 13.61]}
          rotation={[-1.57, 0.06, -2.32]}
          scale={[0.78, 0.78, 0.78]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_47.geometry}
          material={nodes.Cube_47.material}
          position={[-19.75, 51.57, 96.35]}
          rotation={[-1.57, -0.07, -3.09]}
          scale={[1.09, 1.09, 1.09]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={nodes.Cylinder_1.material}
          position={[28.92, -154.53, 59.86]}
          rotation={[0, -Math.PI / 2, 0]}
        />
      </group>
      <group
        position={[-751.9, 178.66, -469.61]}
        rotation={[-0.32, -0.72, -0.47]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_4.geometry}
          material={nodes.Cylinder_4.material}
          position={[28.92, -154.53, 59.86]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_4.geometry}
          material={nodes.Cube_4_4.material}
          position={[-88.94, -26.88, -87.25]}
          rotation={[-1.57, 0.06, -2.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_48.geometry}
          material={nodes.Cube_48.material}
          position={[-28.36, 71, 100.8]}
          rotation={[-1.57, -0.07, -3.09]}
          scale={[1.09, 1.09, 0.94]}
        />
      </group>
      <group position={[64.86, 252.16, -9.63]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_11_2.geometry}
          material={nodes.Cube_11_2.material}
          position={[-264.11, 60.73, -131.45]}
          rotation={[-1.02, -0.28, -0.61]}
          scale={[0.94, 0.94, 1.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_10_2.geometry}
          material={nodes.Cube_10_2.material}
          position={[-318.15, -16.38, 94.75]}
          rotation={[-1.02, -0.28, -0.61]}
          scale={[0.94, 0.94, 1.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_9_4.geometry}
          material={nodes.Cube_9_4.material}
          position={[-249.49, -28.63, 166.34]}
          rotation={[-0.61, -0.01, -0.97]}
          scale={[0.94, 0.94, 1.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_12_2.geometry}
          material={nodes.Cube_12_2.material}
          position={[-316.45, -283.16, 538.56]}
          rotation={[-2.38, 0.59, 1.69]}
          scale={[0.94, 0.94, 0.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_8_2.geometry}
          material={nodes.Cube_8_2.material}
          position={[8.47, -71.25, 241.42]}
          rotation={[-0.61, -0.01, -0.97]}
          scale={[0.94, 0.94, 0.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_12_3.geometry}
          material={nodes.Cube_12_3.material}
          position={[-393.92, -273.16, 501.42]}
          rotation={[-2.34, 0.28, 1.67]}
          scale={[0.94, 0.94, 0.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_7_2.geometry}
          material={nodes.Cube_7_2.material}
          position={[90.91, -61.25, 217.26]}
          rotation={[-0.79, 0.25, -0.95]}
          scale={[0.94, 0.94, 0.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_6_2.geometry}
          material={nodes.Cube_6_2.material}
          position={[310.67, 78.17, -177.34]}
          rotation={[-1.52, -0.24, -1.08]}
          scale={[0.94, 0.94, 0.94]}
        />
      </group>
      <group
        position={[-146.75, 391.37, -326.32]}
        rotation={[-0.13, -0.02, -0.05]}
        scale={[1.2, 1.2, 1.2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_5.geometry}
          material={nodes.Cube_4_5.material}
          position={[-216.3, -10.8, 24.11]}
          rotation={[-1.49, -0.38, -2.85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_5_2.geometry}
          material={nodes.Cube_5_2.material}
          position={[-136.23, -44.36, 153.85]}
          rotation={[-1.38, -0.29, -1.05]}
          scale={[0.78, 0.78, 0.78]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2_5.geometry}
          material={nodes.Cube_2_5.material}
          position={[-32.45, 31.48, -141.5]}
          rotation={[-1.26, 0.03, 1.05]}
          scale={[0.78, 0.78, 0.78]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_49.geometry}
          material={nodes.Cube_49.material}
          position={[-77.97, 107.89, 85.7]}
          rotation={[-1.77, 0.13, 2.98]}
          scale={[1.29, 1.29, 1.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_5.geometry}
          material={nodes.Cylinder_5.material}
          position={[-58.55, -79.71, 59.86]}
          rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
        />
      </group>
      <group
        position={[-554.89, 191.91, -4.7]}
        rotation={[-0.13, -0.02, -0.05]}
        scale={[1.2, 1.2, 1.2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_6.geometry}
          material={nodes.Cylinder_6.material}
          position={[-52.01, -101.81, 59.86]}
          rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_6.geometry}
          material={nodes.Cube_4_6.material}
          position={[-212.31, -20.9, 23.28]}
          rotation={[-1.49, -0.38, -2.85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_5_3.geometry}
          material={nodes.Cube_5_3.material}
          position={[-145.42, -48.09, 158.72]}
          rotation={[-1.38, -0.29, -1.05]}
          scale={[0.78, 0.78, 0.78]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2_6.geometry}
          material={nodes.Cube_2_6.material}
          position={[-32.45, 31.48, -141.5]}
          rotation={[-1.26, 0.03, 1.05]}
          scale={[0.78, 0.78, 0.78]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_50.geometry}
          material={nodes.Cube_50.material}
          position={[-39.21, 106.59, 92.22]}
          rotation={[-1.76, 0.19, 2.98]}
          scale={[1.29, 1.29, 1.29]}
        />
      </group>
      <group
        position={[-1197.33, 163.59, -336.67]}
        rotation={[-0.86, 1.46, 0.93]}
        scale={[0.86, 0.86, 0.86]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_7.geometry}
          material={nodes.Cylinder_7.material}
          position={[-37.2, -151.9, 59.86]}
          rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_7.geometry}
          material={nodes.Cube_4_7.material}
          position={[-286.81, -88.04, 100.05]}
          rotation={[-1.49, -0.38, -1.6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2_7.geometry}
          material={nodes.Cube_2_7.material}
          position={[205.21, -128.14, 20.14]}
          rotation={[-1.35, 0.69, -0.58]}
          scale={[0.78, 0.78, 0.78]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_51.geometry}
          material={nodes.Cube_51.material}
          position={[-58.92, 117.88, 2.86]}
          rotation={[-1.57, -0.07, -3.09]}
          scale={[1.29, 1.29, 1.29]}
        />
      </group>
      <group
        position={[-1037.83, 335.19, -731]}
        rotation={[-0.11, 0.33, -0.06]}
        scale={[1.2, 1.2, 1.2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_52.geometry}
          material={nodes.Cube_52.material}
          position={[-40.37, 65.54, 69.09]}
          rotation={[-1.57, -0.07, -3.09]}
          scale={[1.29, 1.29, 1.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_8.geometry}
          material={nodes.Cylinder_8.material}
          position={[-37.2, -151.9, 59.86]}
          rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2_8.geometry}
          material={nodes.Cube_2_8.material}
          position={[51.79, -39.46, -104.06]}
          rotation={[-1.11, 0.29, -0.88]}
          scale={[0.78, 0.78, 0.78]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_8.geometry}
          material={nodes.Cube_4_8.material}
          position={[-187.69, -35.33, -58.96]}
          rotation={[-1.49, -0.38, -2.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_5_4.geometry}
          material={nodes.Cube_5_4.material}
          position={[45.97, -108.45, 34.72]}
          rotation={[-1.57, 0.06, -1.07]}
          scale={[0.78, 0.78, 0.78]}
        />
      </group>
      <group position={[446.43, 572.89, -308.91]}>
        <group position={[1.68, 249.83, -0.29]} scale={1.27}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_8_3.geometry}
            material={nodes.Cube_8_3.material}
            position={[-36.3, 0, -33.6]}
            rotation={[-Math.PI / 2, 0, -2.3]}
            scale={[-0.58, 0.58, 3.74]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_7_3.geometry}
            material={nodes.Cube_7_3.material}
            position={[-49.75, 0, 1.78]}
            rotation={[-Math.PI / 2, 0, -1.61]}
            scale={[-0.58, 0.58, 3.74]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_6_3.geometry}
            material={nodes.Cube_6_3.material}
            position={[-33.49, 0, 36.35]}
            rotation={[-Math.PI / 2, 0, -0.91]}
            scale={[-0.58, 0.58, 3.74]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_5_5.geometry}
            material={nodes.Cube_5_5.material}
            position={[1.91, 0, 49.89]}
            rotation={[-Math.PI / 2, 0, -0.03]}
            scale={[-0.58, 0.58, 3.74]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4_9.geometry}
            material={nodes.Cube_4_9.material}
            position={[36.46, 0, 34.66]}
            rotation={[-Math.PI / 2, 0, 0.75]}
            scale={[-0.58, 0.58, 3.74]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3_4.geometry}
            material={nodes.Cube_3_4.material}
            position={[49.72, 0, -1.51]}
            rotation={[-Math.PI / 2, 0, 1.62]}
            scale={[-0.58, 0.58, 3.74]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2_9.geometry}
            material={nodes.Cube_2_9.material}
            position={[34.25, 0, -36.39]}
            rotation={[-Math.PI / 2, 0, 2.41]}
            scale={[-0.58, 0.58, 3.74]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_53.geometry}
            material={nodes.Cube_53.material}
            position={[-2.13, 0, -49.25]}
            rotation={[-Math.PI / 2, 0, 2.23]}
            scale={[-0.58, 0.58, 3.74]}
          />
        </group>
        <group position={[0.27, 210.44, 0.98]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_8_4.geometry}
            material={nodes.Cube_8_4.material}
            position={[-62.63, 0, -58.57]}
            rotation={[-Math.PI / 2, 0, -2.34]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_7_4.geometry}
            material={nodes.Cube_7_4.material}
            position={[-3.04, 0, -86.11]}
            rotation={[-Math.PI / 2, 0, -3.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_6_4.geometry}
            material={nodes.Cube_6_4.material}
            position={[58.73, 0, -62.17]}
            rotation={[-Math.PI / 2, 0, 2.55]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_5_6.geometry}
            material={nodes.Cube_5_6.material}
            position={[86.44, 0, -2.57]}
            rotation={[-Math.PI / 2, 0, 1.68]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4_10.geometry}
            material={nodes.Cube_4_10.material}
            position={[64.26, 0, 59.05]}
            rotation={[-Math.PI / 2, 0, 0.89]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3_5.geometry}
            material={nodes.Cube_3_5.material}
            position={[3.3, 0, 86.35]}
            rotation={[-Math.PI / 2, 0, 0.02]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2_10.geometry}
            material={nodes.Cube_2_10.material}
            position={[-58.91, 0, 63.81]}
            rotation={[-Math.PI / 2, 0, -0.77]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_54.geometry}
            material={nodes.Cube_54.material}
            position={[-85.57, 0, 2.43]}
            rotation={[-Math.PI / 2, 0, -0.59]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_4_1.geometry}
          material={nodes.Cylinder_4_1.material}
          position={[1.16, 246.4, 0.34]}
          rotation={[0, -0.75, 0]}
          scale={[1.27, 1.27, 1.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_5_1.geometry}
          material={nodes.Cylinder_5_1.material}
          position={[1.35, 297.95, 0.61]}
          rotation={[-Math.PI, 0.75, -Math.PI]}
          scale={[-0.73, 0.73, 0.73]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_3_1.geometry}
          material={nodes.Cylinder_3_1.material}
          position={[0.47, 217.98, 2.02]}
          rotation={[0, -0.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2_1.geometry}
          material={nodes.Cylinder_2_1.material}
          position={[0, -192.97, 0]}
          rotation={[0, -0.75, 0]}
          scale={[0.85, 0.85, 0.85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_9.geometry}
          material={nodes.Cylinder_9.material}
          position={[-0.29, -265.64, 0.31]}
          rotation={[0, -0.75, 0]}
          scale={[0.85, 0.85, 0.85]}
        />
      </group>
      <directionalLight
        intensity={0.6}
        decay={2}
        color="#fff3eb"
        position={[689.09, 850.57, 401.6]}
        rotation={[-1.13, 0.63, -0.27]}
      />
      <OrthographicCamera
        makeDefault={false}
        far={100000}
        near={-100000}
        position={[302.75, 249.08, 920.91]}
        rotation={[-0.27, 0.27, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ocean.geometry}
        material={nodes.Ocean.material}
        position={[46.83, -180.04, -3.21]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_2.geometry}
        material={nodes.Cylinder_2.material}
        position={[736.48, -129.71, 288.39]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[684.65, -129.71, -333.12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_3.geometry}
        material={nodes.Cylinder_3.material}
        position={[295.43, -80.36, -637.8]}
        rotation={[-Math.PI, -1.2, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud.geometry}
        material={nodes.Cloud.material}
        position={[547.51, 720.1, -1321.1]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_1.geometry}
        material={nodes.Cloud_1.material}
        position={[277.41, 501.97, -1392.69]}
        rotation={[-Math.PI / 2, 0, -1.74]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_2.geometry}
        material={nodes.Cloud_2.material}
        position={[1056.26, 666.48, 578.77]}
        rotation={[0.38, 0.31, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_3.geometry}
        material={nodes.Cloud_3.material}
        position={[1596.85, 677.1, -529.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_4.geometry}
        material={nodes.Cloud_4.material}
        position={[1216.09, 815.7, -579.92]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[284.06, 15.34, 338]}
        rotation={[-0.94, 0.14, -1.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Train.geometry}
        material={nodes.Train.material}
        position={[-13.92, 58.45, 49.46]}
        rotation={[-Math.PI / 2, 0, 2.27]}
      >
        <group
          position={[-573.5, -277.6, -69.59]}
          rotation={[Math.PI / 2, Math.PI / 6, 0]}
        >
          <group position={[-222.31, 14.49, 8.35]} scale={[1, 1, 0.97]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_9_8.geometry}
              material={nodes.Cube_9_8.material}
              position={[-2.78, 0, -79.3]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_7_5.geometry}
              material={nodes.Cube_7_5.material}
              position={[-2.78, 0, 105.01]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_16_3.geometry}
              material={nodes.Cube_16_3.material}
              position={[-0.69, 0, 78.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_15_4.geometry}
              material={nodes.Cube_15_4.material}
              position={[-0.69, 0, 52.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_14_2.geometry}
              material={nodes.Cube_14_2.material}
              position={[-0.69, 0, 25.93]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_13_2.geometry}
              material={nodes.Cube_13_2.material}
              position={[-0.69, 0, -0.35]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_12_4.geometry}
              material={nodes.Cube_12_4.material}
              position={[-0.69, 0, -26.88]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_11_9.geometry}
              material={nodes.Cube_11_9.material}
              position={[-0.69, 0, -52.48]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_10_6.geometry}
              material={nodes.Cube_10_6.material}
              position={[-0.69, 0, -108.37]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
          </group>
          <group position={[-119.73, 14.49, 8.35]} scale={[1, 1, 0.97]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_9_9.geometry}
              material={nodes.Cube_9_9.material}
              position={[0.69, 0, -79.3]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_7_6.geometry}
              material={nodes.Cube_7_6.material}
              position={[0.69, 0, 105.01]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_16_4.geometry}
              material={nodes.Cube_16_4.material}
              position={[-0.69, 0, 78.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_15_5.geometry}
              material={nodes.Cube_15_5.material}
              position={[-0.69, 0, 52.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_14_3.geometry}
              material={nodes.Cube_14_3.material}
              position={[-0.69, 0, 25.93]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_13_3.geometry}
              material={nodes.Cube_13_3.material}
              position={[-0.69, 0, -0.35]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_12_5.geometry}
              material={nodes.Cube_12_5.material}
              position={[-0.69, 0, -26.88]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_11_10.geometry}
              material={nodes.Cube_11_10.material}
              position={[-0.69, 0, -52.48]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_10_7.geometry}
              material={nodes.Cube_10_7.material}
              position={[-0.69, 0, -108.37]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4_11.geometry}
            material={nodes.Cube_4_11.material}
            position={[-170.56, 12.78, -128.52]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3_6.geometry}
            material={nodes.Cube_3_6.material}
            position={[-170.56, 12.78, 128.12]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_11_3.geometry}
            material={nodes.Cube_11_3.material}
            position={[-222.03, -8.96, -68.53]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_9_5.geometry}
            material={nodes.Cube_9_5.material}
            position={[-120.33, -8.96, -68.53]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_11_4.geometry}
            material={nodes.Cube_11_4.material}
            position={[-222.03, -8.96, 110.32]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_5_7.geometry}
            material={nodes.Cube_5_7.material}
            position={[-120.33, -8.96, 110.32]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4_12.geometry}
            material={nodes.Cube_4_12.material}
            position={[-171.38, 30.19, -0.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.99, 0.99, 0.99]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_10_3.geometry}
            material={nodes.Cube_10_3.material}
            position={[-171.38, 36.69, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3_7.geometry}
            material={nodes.Cube_3_7.material}
            position={[-171.38, 13.95, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_4_2.geometry}
            material={nodes.Cylinder_4_2.material}
            position={[-171.55, -45.51, 84.21]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2_2.geometry}
            material={nodes.Cylinder_2_2.material}
            position={[-171.55, -45.51, -90.37]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_3_2.geometry}
            material={nodes.Cylinder_3_2.material}
            position={[-171.55, -45.51, 66.45]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_10.geometry}
            material={nodes.Cylinder_10.material}
            position={[-171.55, -45.51, -108.14]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_55.geometry}
            material={nodes.Cube_55.material}
            position={[-171.55, 0.24, -0.36]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.68, 0.68, 0.41]}
          />
        </group>
        <group
          position={[-625.87, 156.59, -69.59]}
          rotation={[Math.PI / 2, -0.17, 0]}
        >
          <group position={[-222.15, 14.49, 8.35]} scale={[1, 1, 0.97]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_9_10.geometry}
              material={nodes.Cube_9_10.material}
              position={[-2.78, 0, -79.3]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_7_7.geometry}
              material={nodes.Cube_7_7.material}
              position={[-2.78, 0, 105.01]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_16_5.geometry}
              material={nodes.Cube_16_5.material}
              position={[-0.69, 0, 78.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_15_6.geometry}
              material={nodes.Cube_15_6.material}
              position={[-0.69, 0, 52.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_14_4.geometry}
              material={nodes.Cube_14_4.material}
              position={[-0.69, 0, 25.93]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_13_4.geometry}
              material={nodes.Cube_13_4.material}
              position={[-0.69, 0, -0.35]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_12_6.geometry}
              material={nodes.Cube_12_6.material}
              position={[-0.69, 0, -26.88]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_11_11.geometry}
              material={nodes.Cube_11_11.material}
              position={[-0.69, 0, -52.48]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_10_8.geometry}
              material={nodes.Cube_10_8.material}
              position={[-0.69, 0, -108.37]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
          </group>
          <group position={[-119.73, 14.49, 8.35]} scale={[1, 1, 0.97]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_9_11.geometry}
              material={nodes.Cube_9_11.material}
              position={[0.69, 0, -79.3]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_7_8.geometry}
              material={nodes.Cube_7_8.material}
              position={[0.69, 0, 105.01]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_16_6.geometry}
              material={nodes.Cube_16_6.material}
              position={[-0.69, 0, 78.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_15_7.geometry}
              material={nodes.Cube_15_7.material}
              position={[-0.69, 0, 52.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_14_5.geometry}
              material={nodes.Cube_14_5.material}
              position={[-0.69, 0, 25.93]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_13_5.geometry}
              material={nodes.Cube_13_5.material}
              position={[-0.69, 0, -0.35]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_12_7.geometry}
              material={nodes.Cube_12_7.material}
              position={[-0.69, 0, -26.88]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_11_12.geometry}
              material={nodes.Cube_11_12.material}
              position={[-0.69, 0, -52.48]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_10_9.geometry}
              material={nodes.Cube_10_9.material}
              position={[-0.69, 0, -108.37]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4_13.geometry}
            material={nodes.Cube_4_13.material}
            position={[-170.56, 12.78, -128.52]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3_8.geometry}
            material={nodes.Cube_3_8.material}
            position={[-170.56, 12.78, 128.12]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_11_5.geometry}
            material={nodes.Cube_11_5.material}
            position={[-222.03, -8.96, -68.53]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_9_6.geometry}
            material={nodes.Cube_9_6.material}
            position={[-120.33, -8.96, -68.53]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_11_6.geometry}
            material={nodes.Cube_11_6.material}
            position={[-222.03, -8.96, 110.32]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_5_8.geometry}
            material={nodes.Cube_5_8.material}
            position={[-120.33, -8.96, 110.32]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4_14.geometry}
            material={nodes.Cube_4_14.material}
            position={[-171.38, 30.19, -0.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.99, 0.99, 0.99]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_10_4.geometry}
            material={nodes.Cube_10_4.material}
            position={[-171.38, 36.69, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3_9.geometry}
            material={nodes.Cube_3_9.material}
            position={[-171.38, 13.95, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_4_3.geometry}
            material={nodes.Cylinder_4_3.material}
            position={[-171.55, -45.51, 84.21]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2_3.geometry}
            material={nodes.Cylinder_2_3.material}
            position={[-171.55, -45.51, -90.37]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_3_3.geometry}
            material={nodes.Cylinder_3_3.material}
            position={[-171.55, -45.51, 66.45]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_11.geometry}
            material={nodes.Cylinder_11.material}
            position={[-171.55, -45.51, -108.14]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_56.geometry}
            material={nodes.Cube_56.material}
            position={[-171.55, 0.24, -0.36]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.68, 0.68, 0.41]}
          />
        </group>
        <group
          position={[-636.44, -78.53, -69.59]}
          rotation={[Math.PI / 2, 0.09, 0]}
        >
          <group position={[-222.26, 14.49, 8.35]} scale={[1, 1, 0.97]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_9_12.geometry}
              material={nodes.Cube_9_12.material}
              position={[-2.78, 0, -79.3]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_7_9.geometry}
              material={nodes.Cube_7_9.material}
              position={[-2.78, 0, 105.01]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_16_7.geometry}
              material={nodes.Cube_16_7.material}
              position={[-0.69, 0, 78.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_15_8.geometry}
              material={nodes.Cube_15_8.material}
              position={[-0.69, 0, 52.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_14_6.geometry}
              material={nodes.Cube_14_6.material}
              position={[-0.69, 0, 25.93]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_13_6.geometry}
              material={nodes.Cube_13_6.material}
              position={[-0.69, 0, -0.35]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_12_8.geometry}
              material={nodes.Cube_12_8.material}
              position={[-0.69, 0, -26.88]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_11_13.geometry}
              material={nodes.Cube_11_13.material}
              position={[-0.69, 0, -52.48]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_10_10.geometry}
              material={nodes.Cube_10_10.material}
              position={[-0.69, 0, -108.37]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
          </group>
          <group position={[-119.73, 14.49, 8.35]} scale={[1, 1, 0.97]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_9_13.geometry}
              material={nodes.Cube_9_13.material}
              position={[0.69, 0, -79.3]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_7_10.geometry}
              material={nodes.Cube_7_10.material}
              position={[0.69, 0, 105.01]}
              rotation={[-Math.PI / 2, 1.57, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_16_8.geometry}
              material={nodes.Cube_16_8.material}
              position={[-0.69, 0, 78.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_15_9.geometry}
              material={nodes.Cube_15_9.material}
              position={[-0.69, 0, 52.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_14_7.geometry}
              material={nodes.Cube_14_7.material}
              position={[-0.69, 0, 25.93]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_13_7.geometry}
              material={nodes.Cube_13_7.material}
              position={[-0.69, 0, -0.35]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_12_9.geometry}
              material={nodes.Cube_12_9.material}
              position={[-0.69, 0, -26.88]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_11_14.geometry}
              material={nodes.Cube_11_14.material}
              position={[-0.69, 0, -52.48]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 0.14]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_10_11.geometry}
              material={nodes.Cube_10_11.material}
              position={[-0.69, 0, -108.37]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.85, 0.14]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4_15.geometry}
            material={nodes.Cube_4_15.material}
            position={[-170.56, 12.78, -128.52]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3_10.geometry}
            material={nodes.Cube_3_10.material}
            position={[-170.56, 12.78, 128.12]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_11_7.geometry}
            material={nodes.Cube_11_7.material}
            position={[-222.03, -8.96, -68.53]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_9_7.geometry}
            material={nodes.Cube_9_7.material}
            position={[-120.33, -8.96, -68.53]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_11_8.geometry}
            material={nodes.Cube_11_8.material}
            position={[-222.03, -8.96, 110.32]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_5_9.geometry}
            material={nodes.Cube_5_9.material}
            position={[-120.33, -8.96, 110.32]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4_16.geometry}
            material={nodes.Cube_4_16.material}
            position={[-171.38, 30.19, -0.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.99, 0.99, 0.99]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_10_5.geometry}
            material={nodes.Cube_10_5.material}
            position={[-171.38, 36.69, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3_11.geometry}
            material={nodes.Cube_3_11.material}
            position={[-171.38, 13.95, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_4_4.geometry}
            material={nodes.Cylinder_4_4.material}
            position={[-171.55, -45.51, 84.21]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2_4.geometry}
            material={nodes.Cylinder_2_4.material}
            position={[-171.55, -45.51, -90.37]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_3_4.geometry}
            material={nodes.Cylinder_3_4.material}
            position={[-171.55, -45.51, 66.45]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_12.geometry}
            material={nodes.Cylinder_12.material}
            position={[-171.55, -45.51, -108.14]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.9, 4.65, 0.9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_57.geometry}
            material={nodes.Cube_57.material}
            position={[-171.55, 0.24, -0.36]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.68, 0.68, 0.41]}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Train_Rail_1.geometry}
        material={nodes.Train_Rail_1.material}
        position={[-15.53, -70.22, 51.2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Train_Rail_2.geometry}
        material={nodes.Train_Rail_2.material}
        position={[-15.53, -70.62, 51.2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Train_Rail_Base.geometry}
        material={nodes.Train_Rail_Base.material}
        position={[-15.53, -74.62, 51.2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Island_Grass.geometry}
        material={nodes.Island_Grass.material}
        position={[-296.64, 154.08, -282.89]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.27, 1.29, 1.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Island_Rock_Base.geometry}
        material={nodes.Island_Rock_Base.material}
        position={[-299.35, 122.9, -282.89]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.31, 1.31, 1.31]}
      />
    </group>
  );
}

useGLTF.preload("/island_house_copy.gltf");
